/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_evil_mathlib_MathUtils */

#ifndef _Included_com_evil_mathlib_MathUtils
#define _Included_com_evil_mathlib_MathUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_evil_mathlib_MathUtils_add__II
        (JNIEnv *env, jclass jc, jint a, jint b) {
    return a + b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_evil_mathlib_MathUtils_minus__II
        (JNIEnv *env, jclass jc, jint a, jint b) {
    return a - b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_evil_mathlib_MathUtils_multiply__II
        (JNIEnv *env, jclass jc, jint a, jint b) {
    return a * b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    divide
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_evil_mathlib_MathUtils_divide__II
        (JNIEnv *env, jclass jc, jint a, jint b) {
    return a / b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_evil_mathlib_MathUtils_add__DD
        (JNIEnv *env, jclass jc, jdouble a, jdouble b) {
    return a + b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    minus
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_evil_mathlib_MathUtils_minus__DD
        (JNIEnv *env, jclass jc, jdouble a, jdouble b) {
    return a - b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_evil_mathlib_MathUtils_multiply__DD
        (JNIEnv *env, jclass jc, jdouble a, jdouble b) {
    return a * b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    divide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_com_evil_mathlib_MathUtils_divide__DD
        (JNIEnv *env, jclass jc, jdouble a, jdouble b) {
    return a / b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    add
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_evil_mathlib_MathUtils_add__FF
        (JNIEnv *env, jclass jc, jfloat a, jfloat b) {
    return a + b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    minus
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_evil_mathlib_MathUtils_minus__FF
        (JNIEnv *env, jclass jc, jfloat a, jfloat b) {
    return a - b;
}


/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    multiply
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_evil_mathlib_MathUtils_multiply__FF
        (JNIEnv *env, jclass jc, jfloat a, jfloat b) {
    return a * b;
}


/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    divide
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_evil_mathlib_MathUtils_divide__FF
        (JNIEnv *env, jclass jc, jfloat a, jfloat b) {
    return a / b;
}


/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    add
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_evil_mathlib_MathUtils_add__JJ
        (JNIEnv *env, jclass jc, jlong a, jlong b) {
    return a + b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    minus
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_evil_mathlib_MathUtils_minus__JJ
        (JNIEnv *env, jclass jc, jlong a, jlong b) {
    return a - b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    multiply
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_evil_mathlib_MathUtils_multiply__JJ
        (JNIEnv *env, jclass jc, jlong a, jlong b) {
    return a * b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    divide
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_evil_mathlib_MathUtils_divide__JJ
        (JNIEnv *env, jclass jc, jlong a, jlong b) {
    return a / b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    add
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_com_evil_mathlib_MathUtils_add__SS
        (JNIEnv *env, jclass jc, jshort a, jshort b) {
    return a + b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    minus
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_com_evil_mathlib_MathUtils_minus__SS
        (JNIEnv *env, jclass jc, jshort a, jshort b) {
    return a - b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    multiply
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_com_evil_mathlib_MathUtils_multiply__SS
        (JNIEnv *env, jclass jc, jshort a, jshort b) {
    return a * b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    divide
 * Signature: (SS)S
 */
JNIEXPORT jshort JNICALL Java_com_evil_mathlib_MathUtils_divide__SS
        (JNIEnv *env, jclass jc, jshort a, jshort b) {
    return a / b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    add
 * Signature: (BB)B
 */
JNIEXPORT jbyte JNICALL Java_com_evil_mathlib_MathUtils_add__BB
        (JNIEnv *env, jclass jc, jbyte a, jbyte b) {
    return a + b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    minus
 * Signature: (BB)B
 */
JNIEXPORT jbyte JNICALL Java_com_evil_mathlib_MathUtils_minus__BB
        (JNIEnv *env, jclass jc, jbyte a, jbyte b) {
    return a - b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    multiply
 * Signature: (BB)B
 */
JNIEXPORT jbyte JNICALL Java_com_evil_mathlib_MathUtils_multiply__BB
        (JNIEnv *env, jclass jc, jbyte a, jbyte b) {
    return a * b;
}

/*
 * Class:     com_evil_mathlib_MathUtils
 * Method:    divide
 * Signature: (BB)B
 */
JNIEXPORT jbyte JNICALL Java_com_evil_mathlib_MathUtils_divide__BB
        (JNIEnv *env, jclass jc, jbyte a, jbyte b) {
    return a / b;
}

#ifdef __cplusplus
}
#endif
#endif
